### ISSUE TITLE
Add option to auto-select chat box when selecting an emote

### ISSUE THREAD

**Issue by bloons3** [ByzantineFailure/BPM-for-Discord#30]
Currently, the chat box needs to be selected to insert an emote.
Would it be possible to add an option to auto-insert the emote into the chat box?

**Comment by ByzantineFailure** [comment]
Making that a setting is _doable_ but currently all settings in the Discord version directly mirror the BPM options.  This is intentional and all settings functionality outside of the UI (so the settings actually _doing_ things) resides in the core of BPM, which I am loathe to modify more than strictly necessary for a Discord-specific thing.

HOWEVER

It's totally doable to make the Discord version's search box by default target the chat input rather than the currently focused DOM element and I will definitely be looking in to that.  That also would require modifications to core BPM but much less invasive ones.

**Comment by ByzantineFailure** [comment]
IMPLEMENTATION STRATEGY:

In the BPM core:  In `bpm-searchbox.js`, find the on-click handlers for the emote elements in the searchbox.  If `platform === "discord-ext"` trigger a `bpm_backend_message` custom event: `{ method: 'insert_emote', emote: 'EMOTE_NAME' }`

In `discord/addon/core.js`:   In the listener for `bpm_backend_message`, add `insert_emote` to the switch case and fire code to concatenate the emote into the chatbox's text contents if it is on the page.

**Comment by ByzantineFailure** [comment]
Side note:  Really seriously consider renaming `bpm_backend_message`.  It was named that initially as it communicated with the integration code to inject local file HTML, but now that we've migrated to webpack all the code is actually executed in the browser environment.

Maybe something like `bpm_dc_core_message`?

**Comment by ByzantineFailure** [comment]
Support for this added via 92faa3c0e8a3e2aee231985d6ce85d8120be4891 and 87c26d8bb7f23e8123651932571e00dffd39f3b3

Currently this will, in _all cases_ insert the emote's tag into the chat input.  I don't see much call for an option to disable this behavior (and allow you to insert the emote in other input fields).  I will consider making it an option in the event I receive feedback that this is necessary.

**Comment by bloons3** [comment]
Thanks!

**Comment by ByzantineFailure** [comment]
![](http://vignette2.wikia.nocookie.net/foodtest/images/c/c9/Rd_salute.png/revision/latest?cb=20120815211322)
