### ISSUE TITLE
Cannot find module 'Minmist'

### ISSUE THREAD

**Issue by Aquaeyes** [ByzantineFailure/BPM-for-Discord#57]
Sorry to bother, but the only things that show up when I google for this error don't seem to have anything to do with getting this to run, help?

When I run install_windows.bat, this pops up:

![image](https://cloud.githubusercontent.com/assets/10935410/18952642/181a0e2e-867d-11e6-8b2f-2826dd6c9877.png)

Thank you very much.

**Comment by ByzantineFailure** [comment]
No bother!

Every time I have seen this error in the past it has indicated to me that the user has downloaded the source code rather than the actual compiled add-on.  Looking at the path to `index.js` in the stack trace, that also seems to be the case.

Ensure you have downloaded the compiled addon code from the downloads page -- it should end in `.7z`.  As of writing this, [this is the current version of BPM's compiled  code](https://github.com/ByzantineFailure/BPM-for-Discord/releases/download/discord-v0.8.11-beta/BPM.for.Discord.discord-v0.8.11-beta.7z).

Once downloaded, ensure you unpack it before trying to install.  I recommend using [the program 7z to do this](http://www.7-zip.org/).

Hope this helps!

**Comment by Aquaeyes** [comment]
It did, thanks you, and sorry for taking up your time.

Thanks again!

**Comment by ByzantineFailure** [comment]
Ha-ha, no problem!  I had to wait on the train due to delays anyway.
