### ISSUE TITLE
Instruction Improvement

### ISSUE THREAD

**Issue by JetstreamGW** [ByzantineFailure/BPM-for-Discord#87]
Howdy. I know what I'm about to say will annoy someone, because "people should know better."

However! I would like to note that the Instructions for installing BPM could maybe possibly be better. In specific, there should be something about letting the .bat run until it tells you it's done cleaning up.

See, when you run the .bat, it says "Installation complete!" And then sits there for several seconds.

Assuming that, y'know, install was complete, I closed the window and reloaded Discord. Discord, of course, immediately stopped working and I had to reinstall.

It wasn't until I used the .exe installer and watched it do its thing that I realized that more stuff happens after "Installation Complete!"

So I suggest that more detail be added to the instructions. OR, change the output to "Installation complete, please wait."

**Comment by ByzantineFailure** [comment]
I actually thought that earlier today.  Will make a note to fix it in the
code base.

On Jul 23, 2017 9:34 PM, "JetstreamGW" <notifications@github.com> wrote:

Howdy. I know what I'm about to say will annoy someone, because "people
should know better."

However! I would like to note that the Instructions for installing BPM
could maybe possibly be better. In specific, there should be something
about letting the .bat run until it tells you it's done cleaning up.

See, when you run the .bat, it says "Installation complete!" And then sits
there for several seconds.

Assuming that, y'know, install was complete, I closed the window and
reloaded Discord. Discord, of course, immediately stopped working and I had
to reinstall.

It wasn't until I used the .exe installer and watched it do its thing that
I realized that more stuff happens after "Installation Complete!"

So I suggest that more detail be added to the instructions. OR, change the
output to "Installation complete, please wait."

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ByzantineFailure/BPM-for-Discord/issues/87>, or mute
the thread

**Comment by ByzantineFailure** [comment]
Actually on further reflection this is just an issue wiht me not properly doing async in the packing code.  Derp.
