### ISSUE TITLE
Search button fails to appear if `searchButtonTopRight` is enabled.

### ISSUE THREAD

**Issue by Jibodeah** [ByzantineFailure/BPM-for-Discord#93]
Discord Canary. Probably affects release too since it's been like this for a little while.

Additionally, the actual toggle for this setting doesn't seem to be in the settings window. (I had to go into Electron's developer tools and access the local storage to change it!)

**Comment by ByzantineFailure** [comment]
To confirm, does it come back up once you've refreshed Discord or is it permanently gone?

I need to re-add this to the settings window regardless.  I should have some time to fix this starting around Friday when I enter my funemployment period between my current job and my new one :)

**Comment by Jibodeah** [comment]
My testing was...

1. `searchButtonTopRight: true` - Button does not appear
2. Toggled `searchButtonTopRight` to `false` - Button does not *yet* appear
3. Refreshed Discord via `Ctrl+R` - Button **does** appear.

**Comment by ByzantineFailure** [comment]
Okay, cool.  That is the expected behavior from when the setting was created.  There's some technical limitations about actually creating the button without a refresh -- it's _doable_ but would be way more trouble than it's worth and create a huge surface for bugs.

Scope of this issue is to re-add the setting to the settings page and give it a proper description again.

**Comment by ByzantineFailure** [comment]
Setting re-added, query selectors updated to fix this issues.  Will go out in the next update.  Checking with Typhos if there's one coming up soon otherwise will push out independently.
